### ISSUE TITLE
Error: Requiring unknown module "art/core/color"

### ISSUE THREAD

**Issue by davidskaarup** [bgryszko/react-native-circular-progress#1]
I get the following error after following the install instructions:

Error: Requiring unknown module "art/core/color". If you are sure the module is there, try restarting the packager.

Am I missing something? (I have tried restarting the packager)

**Comment by bgryszko** [comment]
Are you trying to use it in the existing project or in example project? Looks like art lib isn't there. Did you `npm install`? You can also try `npm install art`. Let me know if it helps.

**Comment by davidskaarup** [comment]
You're right, I was missing the art lib - it's working now. Thanks :+1:

**Comment by bgryszko** [comment]
You're welcome
