### ISSUE TITLE
Reset progressbar without 'return' animation?

### ISSUE THREAD

**Issue by mkpietrzyk** [bgryszko/react-native-circular-progress#102]
Hello!

I would like to ask if there is any possibility to reset the progressbar without the returning animation? 

My desire solution is:
-----------xxxxxxxx (60%) -> xxxxxxxxxxxxxxxxxx ( 0% ) (no animation, pure reset)
Current default solution using the lib is:
-----------xxxxxxxx (60%) -> -------xxxxxxxxxxxx (40% ) -> -----xxxxxxxxxxxxxx (20% ) 
etc... (it goes back quickly... but it's annoying unfortunately...)

**Comment by bgryszko** [comment]
For your case it's annoying, for others it might be desired :)

You could create your own animation component that wraps CircularProgress based on https://github.com/bgryszko/react-native-circular-progress/blob/master/src/AnimatedCircularProgress.js & make use of `componentDidUpdate` (https://github.com/bgryszko/react-native-circular-progress/blob/master/src/AnimatedCircularProgress.js#L20) where you would decide if animate the component or set a fix value.

**Comment by mkpietrzyk** [comment]
Thanks! Sorry mate, did not want to sound rude of course! :)

**Comment by pckz** [comment]
@mkpietrzyk how do you solved that? I need the same. Reset without animation

**Comment by mkpietrzyk** [comment]
> @mkpietrzyk how do you solved that? I need the same. Reset without animation

HI! I am sorry I left the team where the solution was implemented last year so I don't remember. My teammate made a proper fix for it next week this question was asked. I think we used componentDidUpdate with proper animation / re-rendering asset, can't tell you the details because I just don't remember :(

**Comment by tomerzcod7** [comment]
Did you guys solve this yet? (For react, not react-native)
