### ISSUE TITLE
AnimatedCircularProgress children(fill) TypeError

### ISSUE THREAD

**Issue by dahudson88** [bgryszko/react-native-circular-progress#103]
I am getting the following error when the AnimatedCircularProgress is being rendered...

Debug Mode: ![simulator screen shot - iphone 8 - 2017-11-30 at 13 41 04](https://user-images.githubusercontent.com/31221472/33448466-1fa62ce8-d5d4-11e7-933b-5c047e78d7cc.png)

Release Mode: TypeError: f is not a function. (In 'f(k)', 'f' is an instance of Object)

Initially I was getting the errors defined [https://github.com/bgryszko/react-native-circular-progress/issues/86](url)

I have updated my package.json to -> "react-native-circular-progress": "https://github.com/bgryszko/react-native-circular-progress.git#master",

USAGE:
 ```
                     <AnimatedCircularProgress
                        size={215}
                        width={20}
                        fill={this.state.progressFill}
                        tintColor="#f77b00"
                        backgroundColor="#dddddd"
                        tension ={5}
                        friction ={30}
                        style={styles.circularProgress}>
                        <Text style= {styles.circularProgressText} >
                        {this.state.progressText.split(" ").join("\n")}
                        </Text>
                      </AnimatedCircularProgress>
```

I am unsure what could be causing this TypeError.  Any ideas?

**Comment by Jacse** [comment]
In your code the children of `AnimatedCircularProgress` is a component (Text-component). It should be a *function* that returns a component instead. E.g:

```js
<AnimatedCircularProgress
  size={215}
  width={20}
  fill={this.state.progressFill}
  tintColor="#f77b00"
  backgroundColor="#dddddd"
  tension ={5}
  friction ={30}
  style={styles.circularProgress}
>
    (fill) => (
      <Text style= {styles.circularProgressText} >
        {this.state.progressText.split(" ").join("\n")}
      </Text>
    )
</AnimatedCircularProgress>
```

It doesn't make a lot of sense to use the children-prop in this way, and that is something I hope to adress soon (moving the function to a prop).
