### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by jemise111** [bgryszko/react-native-circular-progress#11]
Using this with RN 0.19.0.

Works great on iOS:

![image](https://cloud.githubusercontent.com/assets/4265163/12861598/8d91c044-cc32-11e5-83b4-36f4fc0b46cf.png)

And RN added ART support on Android as of 0.18.0. (https://github.com/facebook/react-native/releases/tag/v0.18.0)

But there's an issue rendering on Android (Genymotion):

![image](https://cloud.githubusercontent.com/assets/4265163/12861616/b3eca9de-cc32-11e5-813f-abb6c5e1f757.png)

Maybe just an issue with RN ART on Android but I can't tell. Thanks!

**Comment by tuan23** [comment]
I'm having the same issue too. Looking forward for a fix.

**Comment by gunters63** [comment]
Problem is the module uses the strokeDash feature of ReactART to limit the length of the drawn Path. 

strokeDash is not supported for Android yet.

But it should be fairly easy to draw the circle without strokeDash by adjusting the circlePath to draw only the needed part(s) of the arc(s).

**Comment by gunters63** [comment]
I have a working solution now for Android which does not use strokeDash anymore.
It requires directly manipulating the internal path array of ReactNativeART Path, because this seems to artificially limit arc to half circles.

Here is a circlePath which will return a correct arc path with start and end angle.
````
function circlePath(cx, cy, r, start, end) {
    let p = Path();
    p.path.push(4, cx, cy, r, start * Math.PI / 180, (start - end) * Math.PI / 180, 0);
    return p;
}
````

**Comment by gaykov** [comment]
@gunters63 amazing solution, thanks! Are you going to create a PR?

**Comment by gunters63** [comment]
PR created :)

**Comment by gaykov** [comment]
@gunters63 thanks! @bgryszko could you update the npm version?

**Comment by gunters63** [comment]
Until that happened you could also use:

````
    "react-native-circular-progress": "bgryszko/react-native-circular-progress#HEAD",
````

in your package.json

**Comment by bgryszko** [comment]
@gaykov npm updated! Thanks again @gunters63
