### ISSUE TITLE
How to draw a line inside circular progress

### ISSUE THREAD

**Issue by ShaikhKabeer** [bgryszko/react-native-circular-progress#111]
How can I achieve like this as given in below chart image

![33873112-b2efb50e-df3f-11e7-8c6d-d8c600bdd98f](https://user-images.githubusercontent.com/29751540/34867979-3bf1a922-f7a8-11e7-8b33-6bcdc3f44aa6.png)

**Comment by ShaikhKabeer** [comment]
Guys, any solution to this ?

**Comment by Jacse** [comment]
That is not currently possible with this library. Unless there is suddenly a lot of people requesting this feature I unfortunately don't think we'll be adding it.

**Comment by ShaikhKabeer** [comment]
@Jacse , can you please suggest how can I do it ?

**Comment by Jacse** [comment]
As I said before, @ShaikhKabeer, it is not currently possible. The only way to achieve this would be to modify the library.
