### ISSUE TITLE
Warning when fill is given from Animated.timing

### ISSUE THREAD

**Issue by Culzean** [bgryszko/react-native-circular-progress#112]
I get this warning,
Failed prop type, Invalid prop 'fill'of type 'object' supplied to 'AnimatedCircularProgress', expected 'number'.

This is the call to Animated.timing: 

```
componentWillReceiveProps(props) {
        this.state.spinValue.setValue(0.0)
        if (props.capturing_state == "inProgress") {
            Animated.timing(
                this.state.spinValue,
            {
                toValue: 100,
                duration: 2000,
            }
            ).start();

            this.state.fillAmount = this.state.spinValue.interpolate({
                inputRange: [0,100],
                outputRange: [0, 100]
            });
        }
    }
}
```

And how the value is assigned.

```
                <AnimatedCircularProgress
                size={64}
                width={6}
                fill={this.state.spinValue}
                tintColor="#00e0ff"
                backgroundColor= "#778899" />
```

However this gives the result as desired. The warning is distracted through. Any ideas how to sort this? I understand that .interpolate() returns an object and hides the value. This works correctly with style transforms.

**Comment by Culzean** [comment]
I edited the typescript types for this property to remove the warning.

**Comment by jalal246** [comment]
@Culzean i have the same issue as well

**Comment by Jacse** [comment]
Closing since this is not relevant with version 1.0.0

**Comment by Jacse** [comment]
But for the record you can always create your own animated component from the circularprogress-component and controll the fill-prop that way.
