### ISSUE TITLE
 Linting error  AnimatedCircularProgress not found in 'react-native-circular-progress'

### ISSUE THREAD

**Issue by deejaygeroso** [bgryszko/react-native-circular-progress#116]
`import {  AnimatedCircularProgress } from 'react-native-circular-progress';`
gives me an error when I run linting on my machine.
`error AnimatedCircularProgress not found in 'react-native-circular-progress'`

**Versions:**
"react-native-circular-progress": "^0.1.2",
"react": "16.0.0",
"react-native": "0.51.0",
lint: version 26.0.2

**My .eslintrc rules:**
```
 "rules": {
      "react/display-name": 0,
      "import/default": 0,
      "no-console": 1,
      "comma-dangle": 0,
      "import/extensions": 0,
      "import/no-absolute-path": 0,
      "import/no-unresolved": [2, {
        "ignore": [ "^/src", "/", ]
      }],
      "import/no-extraneous-dependencies": ["error", { "devDependencies": true }]
    }

```

**Comment by Jacse** [comment]
This doesn't seem like an issue with the library but rather your linting setup. To ignore the wrong error, you could use `// eslint-disable-line` or something similar.
