### ISSUE TITLE
Weird Circular Drawing on Android only

### ISSUE THREAD

**Issue by JakeRawr** [bgryszko/react-native-circular-progress#117]
<img width="249" alt="screen shot 2018-03-01 at 4 01 58 pm" src="https://user-images.githubusercontent.com/7199499/36876501-2be16d1e-1d6a-11e8-9749-1332f90f1532.png">

Updated React Native from 0.41 to 0.52
and updated react-native-circular-progress from 0.0.8 to 0.1.2

then react-native-circular-progress on android started to draw weird AND when there's animation, it's going counterclockwise.

iOS works fine

**Comment by Jacse** [comment]
Would it be possible for you to post some code? I can't seem to reproduce this in the example.

**Comment by Jacse** [comment]
Actually, please post your code in #107. It's the same issue.
