### ISSUE TITLE
Possible to change animation FPS?

### ISSUE THREAD

**Issue by jLynx** [bgryszko/react-native-circular-progress#118]
Is it possible to change the animation FPS to something a little smoother like 60FPS?

Great project by the way!

**Comment by Jacse** [comment]
This library uses react native's [Animated](https://facebook.github.io/react-native/docs/animated.html) which does all the animation. It is not possible to change the FPS, but it should be pretty smooth around the ≈60.

**Comment by jLynx** [comment]
In that case, this relates to #119
