### ISSUE TITLE
Poor Android performance 

### ISSUE THREAD

**Issue by jLynx** [bgryszko/react-native-circular-progress#119]
I have tired this on both iOS and Android. On iOS it seems to run super smoothly at about 60fps but when I run the same project on android it seems to be really gittery running around 25-30fps.

Is this a known issue, or is there a fix for it?

**Comment by Jacse** [comment]
It is not a know issue, no. Do you perform any logging on Android? That severly limits performance. Also you could try running a production build and see if the performance issue persists.

**Comment by jLynx** [comment]
I am not preforming any logging, but I will build the APK and test that out and get back to you

**Comment by jLynx** [comment]
I tried the performanc on the build APKe, its like 10x better, but just not as buttery smooth as iOS. Still a bit jittery

**Comment by Jacse** [comment]
It seems performance could be improved. I'm closing this issue to keep discussion on performance on #121 .
