### ISSUE TITLE
Multiple progressbars

### ISSUE THREAD

**Issue by kayson** [bgryszko/react-native-circular-progress#121]
I am using the circular progress bar in every component of a listview. Resulting in sometimes up to 90 unique progress bars. This result in very slow app performance and lagging behaviors. Is this a known issue and is there any way to solve this?

This is an example of how I use it:
`<AnimatedCircularProgress
  size={42}
  width={4.5}
  fill={fill}
  rotation={0}
  linecap='round'
  tintColor={bgColor}
  backgroundColor="#f3f3f3" />`

I have tested in multiple devices, including an iPhone 8 Plus and in release build. 

Thanks

**Comment by Jacse** [comment]
It seems we have some performance issues and we'll need to look into how performance could be improved. I've created #127 to track progress towards version 2.0.0 and one of the things I would like to do is compare the current ART-based approach to one based on `react-native-svg` and see if performance could be improved that way.

**Comment by Jacse** [comment]
Now we've moved to a `react-native-svg`-based solution I'll close this. Having 20+ unique progressbars might still prove unwise because of the performance implications but at this point I don't know how to significantly improve performance.
