### ISSUE TITLE
Loses progress on loss of focus

### ISSUE THREAD

**Issue by jLynx** [bgryszko/react-native-circular-progress#123]
On iOS if you are to swipe down from the notification center and swipe back up so you can see your app you will notice that the progress gets reset.

On Android if you press the home button and then open the app again it will also reset the progress.

This seems like a bug to do with loss of focus. Is there currently a fix for this?

**Comment by vzaffalon** [comment]
same problem here please helpp

**Comment by vzaffalon** [comment]
just change performLinearAnimation to performTimingAnimation and the problem was fixed

**Comment by Jacse** [comment]
Do you still experience this @jLynx?

**Comment by Jacse** [comment]
This shouldn't happen with the newest version. Please re-open if it does.
