### ISSUE TITLE
Animation starts on render rather than when button is pressed

### ISSUE THREAD

**Issue by ChelseaDan** [bgryszko/react-native-circular-progress#124]
I'm trying to emulate the SnapChat feature of showing a red circle around the capture button when recording, but with the current way I'm doing it, the animation starts as soon as the component is rendered and then `onAnimationComplete` is logged, after that it's not possible to use `this.refs.circularProgress.performLinearAnimation(100, 2000);`.

The relevant code is here below, maybe I'm doing something stupid:

https://snack.expo.io/Byw-mCQKf

Hopefully someone will be able to guide me in the right direction.

**Comment by Jacse** [comment]
What I think you're doing here is setting `fill` to 100 on mount. You probably want to set `fill` to be zero initially and then start the animation with `performLinearAnimation`

**Comment by ChelseaDan** [comment]
Hi Jacse, thanks for the response. I'll give it a go and let you know whether it helped. Thanks again.

**Comment by Jacse** [comment]
@ChelseaDan did it work?

**Comment by Jacse** [comment]
Closing. Let me know if it didn't work.
