### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by Jacse** [bgryszko/react-native-circular-progress#127]
I've been considering introducing some breaking changes and moving the library to version 1.0.0.

Breaking changes:
1. - [x] Ability to specify easing in animation (#125)
2. - [ ] ~~Remove children prop, move to `renderChild`-prop (doesn't make sense to pass a function as a child)~~
3. - [x] Only render background circle when a `backgroundColor`-prop has been passed ([reason](https://github.com/bgryszko/react-native-circular-progress/commit/454048bd92a166b876d53ea227c6cff2cc43c41a#commitcomment-26534558))
4. - [x] Rename `linecap`-prop to camelCase
5. - [x] Merge `onAnimationComplete` and `onLinearAnimationComplete`
6. - [x] Consider moving to `react-native-svg` (we have performance issues with ART, maybe svg does better. Will need to be tested)
7. - [x] Rename `performTimingAnimation` to `animate`

Would like to hear feedback before moving on. @markusl

**Comment by markusl** [comment]
Sounds good to me! Existing users can stay at the current version if they don't want to upgrade. I think quite many of those points are indeed good to implement

**Comment by Jacse** [comment]
I've pushed a few commits which cross off some of the items on the list - none have been tested yet. I added the 5th point about merging the two props `onAnimationComplete` and `onLinearAnimationComplete` (the first firing after automatic initial animation and the latter firing after a manual animation). What are your thoughts on that, @markusl?

**Comment by JulianKingman** [comment]
I took care of item 6 for you :)
https://github.com/bgryszko/react-native-circular-progress/pull/132

**Comment by Jacse** [comment]
I'm considering scratching item 2 and continue using functions-as-child-components after reading blog posts like [this one](https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9). Any thoughts? If not, I'll revert my changes to the `renderChild`-prop.

**Comment by Jacse** [comment]
I've pushed some updates and it looks like we've made the list. For simplicity, I've removed the sping-based animation and migrated to a timing-based one. I'm unsure if we should have sticked with two different animations... @markusl @JulianKingman let me know what you think. If you could test it out that'd be great as well.

**Comment by Jacse** [comment]
Since there has been no response, I went ahead and published on NPM
