### ISSUE TITLE
On press event on circle 

### ISSUE THREAD

**Issue by yeomann** [bgryszko/react-native-circular-progress#134]
Hi,

is there any onpress props on the circle? There should be I believe! I have tried wrapping this way. 

`<TouchableWithoutFeedback onPress={this.onPressGraphics}>
					<View style={styles}>
						<AnimatedCircularProgress
							ref="graphicsProgress"
							size={170}
							width={3}`
 
but it seems buggy, on emulator (IOS and android) event is firing all good but on real device of android whenever I click on Circle nothing happens and chaotically all of the screen becomes non- clickable that means, no other event is being recognised in who screen of android. super frustrating.

for <view> inside I already tried to give it fixed width and overflow hidden like so
```
width: 170,
overflow: "hidden"
``` 

but same results once I clicked on circle who screen becomes useless. non-clickable.

does anyone else have encounter? or how you are handling on press event on circle graphics. thank you for reading.

**Comment by yeomann** [comment]
I would be interested to know the answer why there's isn't do you mind if I create a PR for that? 
I solved my above mentioned problem but I am wondering why there's isn't OnPress event for circle

**Comment by Jacse** [comment]
@yeomann do you mind sharing how you solved your problem in case somebody comes along experiencing the same? There is no `onPress` event exactly because people can wrap the component themselves if they so please.

**Comment by yeomann** [comment]
let me get my example in few minutes @Jacse but why don't didn't we consider this feature yet? :)

**Comment by Jacse** [comment]
@yeomann we're not adding this feature because people can wrap the component themselves if they need that behaviour. We try to keep each component as modular as possible.

**Comment by yeomann** [comment]
although I believe this feature should come from out of the box, anyways, here's a little screenshot for those who wants to do so. 
<img width="505" alt="screen shot 2018-07-08 at 23 21 51" src="https://user-images.githubusercontent.com/5970751/42423617-d58d4c88-8305-11e8-8935-8f14a7ff3b61.png">
