### ISSUE TITLE
"PropTypes.isRequired" not working?

### ISSUE THREAD

**Issue by jamesqo** [bgryszko/react-native-circular-progress#135]
Hi, I'm a first-time user of your library and when I tried pasting this code in my app

```jsx
<AnimatedCircularProgress ref={this.circularProgress} />
```

I got this error:

![screenshot_20180626-203128](https://user-images.githubusercontent.com/9159214/41985664-f31743c4-7a01-11e8-9e46-3eefc5a3e683.png)

I spent a couple of hours scratching my head about this. I thought it must be a runtime bug and was about to report it when I finally realized that it was because I had forgotten to pass in these attributes: https://github.com/bgryszko/react-native-circular-progress/blob/master/src/CircularProgress.js#L96-L98

It seems that for whatever reason, `.isRequired` on those props is not behaving properly and giving a error like it should be, resulting in a poor first experience for users who forget to specify them.

**Comment by Jacse** [comment]
This should be fixed in the current version. Please reopen if you still experience this in version `1.0.1`.
