### ISSUE TITLE
Request: Add option to disable animation on load

### ISSUE THREAD

**Issue by jamesqo** [bgryszko/react-native-circular-progress#137]
This component performs its animation right away in `componentDidMount()`, but I want to delay that for a few ms when my screen loads. It would be nice to add a prop like

```jsx
<AnimatedCircularProgress ... animateOnLoad={false} />
```

to allow me to disable this behavior.

**Comment by jamesqo** [comment]
Another option (not necessarily incompatible with this) would be to add a `delay` parameter.

**Comment by Jacse** [comment]
What I suggest you do is simply set `fill={0}` and update the prop when you want the animation to start.

**Comment by jamesqo** [comment]
@Jacse If the animation takes, say, 2sec by default then would this disable animations for the first 2 sec because it's busy doing an animation from 0 to 0? Or would React Native detect that the start and end values are the same and not bother with an animation?

**Comment by Jacse** [comment]
That's true. What I suggest doing then is simply creating your own animated component and controlling the fill prop yourself like so: `const AnimatedProgress = Animated.createAnimatedComponent(CircularProgress);`

**Comment by Jacse** [comment]
I'll be closing this since it's not actionable.

**Comment by Makgora** [comment]
Up ! If the animation starts on load, it's impossible to get the animation object and so impossible to stop it.

If your timer start when you arrive on a particular page, if the user access to this page, then press back and access again, and again, it creates a lot of circular progress...
