### ISSUE TITLE
Props don't get applied

### ISSUE THREAD

**Issue by Ahagan** [bgryszko/react-native-circular-progress#139]
VERSION: 0.2.0
React Native: 0.55.x

When trying to apply the following props, they make no effect:

-rotation. If I set it to 0, I would expect the animation to start from the top, not at the 90def default value.
-- I have add to add a custom style to rotate

- lineCap. If I set it to 'round', the change doesn't appear.

Example code:
`
    render() {
        return ( <AnimatedCircularProgress
            size={150}
            width={15}
            style={{
                transform: [{ rotate: '-90deg' }]
            }}
            fill={this.props.percentage}
            tintColor="#BA0010"
            lineCap="round"
            onAnimationComplete={() => console.log('onAnimationComplete')}
            backgroundColor="white">
            {
                (fill) => (
                    (this.props.centralIconName) &&
                    <Icon style={{ fontSize: 60, transform: [{ rotate: '90deg' }] }} name={this.props.centralIconName} />
                )
            }
        </AnimatedCircularProgress>)
    }
`

**Comment by Jacse** [comment]
Do you still experience this with the newest version?

**Comment by Jacse** [comment]
Closing for now, feel free to reopen.
