### ISSUE TITLE
Last changes don't exist in 2.0

### ISSUE THREAD

**Issue by maxfadeev** [bgryszko/react-native-circular-progress#140]
Hello!
Could you take a look and tag it, please ? Thanks!

**Comment by maxfadeev** [comment]
So in the following example a duration doesn't work
`javascript
<AnimatedCircularProgress
    size={30}
   width={10}
   fill={100}
   duration={10000}
   tintColor="#00ff00"
/>
`

**Comment by maxfadeev** [comment]
Yes you are right. I looked at the last version on github at first, and couldn't understand why the duration prop wasn't working :) Now I see it differs from the npm version.

**Comment by Jacse** [comment]
Version `1.0.0` is now on NPM 😄
