### ISSUE TITLE
Animate is not a function

### ISSUE THREAD

**Issue by kyhnlbyrk** [bgryszko/react-native-circular-progress#142]
Hi, 

First of all, thank you for this component. It is very good. However, I can not change the animation with
refs, and animate() function.. React native says that animate is not a function. I am on Expo.. Do you know about this issue?

**Comment by shaheermir** [comment]
Had to dig through the source code to find it. The function has been changed to 'performLinearAnimation (toValue, duration)'.

As of it right now, it doesnt accept an easing funtion, instead its hardcoded to linear, as indicated by the function name.

**Comment by Jacse** [comment]
This happened because version 1.0.0 wasn't published to npm yet. It has now been published, please update 👍
