### ISSUE TITLE
Native component for "RNSVGPath" does not exist 

### ISSUE THREAD

**Issue by janaka120** [bgryszko/react-native-circular-progress#146]
I got this error message after import AnimatedCircularProgress component. 

![capture](https://user-images.githubusercontent.com/10891893/42613100-b0d2da66-85bc-11e8-9d8a-914d1de49156.PNG)

My project config.
```
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-circular-progress": "^1.0.0",

```    
If anyone know how to solve this problem. Please help me.

**Comment by infostreams** [comment]
Do this

`npm install react-native-svg --save`
`react-native link react-native-svg`

And then follow you can build it but get a build error, which can be resolved with the instructions here 
https://github.com/react-native-community/react-native-svg/issues/544#issuecomment-355190129

After that the RNSVGPath error disappears.

**Comment by janaka120** [comment]
Thank you very much @infostreams . I'll give a try and let you know.

**Comment by Jacse** [comment]
I've updated the reame to make the requirement more clear.
