### ISSUE TITLE
can't find the variable: Easing

### ISSUE THREAD

**Issue by janaka120** [bgryszko/react-native-circular-progress#148]
When I call onSubmit() on button press, it returns this error msg
`**Can't find variable: Easing**`

I import AnimatedCircularProgress like this.
`import { AnimatedCircularProgress } from 'react-native-circular-progress';`

This is my code. 
```
constructor() {
    super();
    this.circularProgressRef = React.createRef();
    this.onSubmit = this.onSubmit.bind(this);
}
onSubmit() {
    this.circularProgressRef.animate(100, 8000, Easing.quad);
}

render(){
  return(
    <AnimatedCircularProgress
      ref={this.circularProgressRef}
      size={120}
      width={15}
      fill={100}
      tintColor="#00e0ff"
      onAnimationComplete={() => console.log('onAnimationComplete')}
      backgroundColor="#3d5875" />
     );
  }
```
**package.json**
```
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-circular-progress": "^1.0.0",
    "react-native-svg": "^6.4.1",
```
I need to animate **AnimatedCircularProgress** when I click the button.
If someone knows how to do this, please help me.
Thank you.

**Comment by Jacse** [comment]
You need to import Easing first like so:
```js
import {
  Easing
} from 'react-native';
```

**Comment by janaka120** [comment]
Thanks @Jacse . I added your answer. Then I got this error.

`undefined is not a function (evaluating ' _this.circularProgressRef.animate(100, 8000, _reactNative.Easing.quad)')`

Thank you.
