### ISSUE TITLE
Circle size autoscale?

### ISSUE THREAD

**Issue by LongPotato** [bgryszko/react-native-circular-progress#15]
Is there anyway to make the circle auto scale its size base on the device screen size?

Currently my work around for this, is to determine the screen size and manually set the size value for circle.

**Comment by LongPotato** [comment]
Also I am looking for away to make the text inside the circle always in the middle, despite the device screen size.

Thanks

**Comment by Jacse** [comment]
Is there any reason you closed this issue @LongPotato? I would like to hear whether it is possible to have an autoscaling circle.
