### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by AylwSt01** [bgryszko/react-native-circular-progress#151]
trying to use this in a project, and when running in Storybook i get the following error.
The debugger points me to line 4.

![image](https://user-images.githubusercontent.com/20923612/43839324-bb3e0f20-9b15-11e8-8a9b-6e8ca225cfa7.png)

**Comment by AylwSt01** [comment]
i fixed the issue in node_module by changing the import lines to:
```
import { default as CircularProgress } from './src/CircularProgress';
import { default as AnimatedCircularProgress } from './src/CircularProgress';
```
any chance this library can be updated to reflect this change?

**Comment by Jacse** [comment]
Moving to #152
