### ISSUE TITLE
support for android?

### ISSUE THREAD

**Issue by cmdillon** [bgryszko/react-native-circular-progress#18]
hi! great component! any chance now that there is art support that there will be a android version soon?

**Comment by tomauty** [comment]
I believe it does already work for android.

**Comment by cmdillon** [comment]
hi! thanx for the feedback. do you know or have an example of how to get it up and running in android?

**Comment by dantman** [comment]
It worked right away in Android for me, not sure if that's because I ran `rnpm link` anyways.

**Comment by powerc9000** [comment]
This works for me on android

**Comment by cmdillon** [comment]
yup, works!
