### ISSUE TITLE
No component found for view with name "ARTSurfaceView"

### ISSUE THREAD

**Issue by shiv86** [bgryszko/react-native-circular-progress#23]
Using:
    "react-native": "^0.24.1",
       "react-native-circular-progress": "0.0.6",

I get the following error below:

<img width="470" alt="screen shot 2016-05-21 at 4 58 34 pm" src="https://cloud.githubusercontent.com/assets/1146219/15451408/49ac3b98-1f75-11e6-92f4-fe9718c88ddb.png">

**Comment by sschengyf** [comment]
I have the same issue, I guess it is a problem caused by react-native-progress library

**Comment by Leeds-eBooks** [comment]
I did and I am getting this error. Is there an easy way to check that it has linked correctly? `rnpm link` returned no errors.

**Comment by dionysiusmarquis** [comment]
I drag and dropped `node_modules/react-native/Libraries/ART/ART.xcodeproj` somewhere to my Xcode project. After that I was able to add `libART.a` under `Build Phases` -> `Link Binary With Libraries`

**Comment by sschengyf** [comment]
@shiv86 
I have found the solution for this problem.
It is caused by ART library which is to draw vector graphics using React.
You do not need to download anything, ART library is already in React-Native libraries.
Merely linking it to your project via Xcode can resolve the problem.  
This article provides detailed steps, [https://www.smashingmagazine.com/2016/04/how-to-build-your-first-ios-app-with-javascript/](https://www.smashingmagazine.com/2016/04/how-to-build-your-first-ios-app-with-javascript/)

**Comment by RezaRahmati** [comment]
@sschengyf  @dionysiusmarquis  Thanks it solves my issue too 👍

**Comment by bgryszko** [comment]
Glad to hear it solves your issue. @dionysiusmarquis @sschengyf thanks for support!

**Comment by mschipperheyn** [comment]
@sschengyf that links doesn't work (or needs a subscription or something)

**Comment by sampocs** [comment]
@dionysiusmarquis @sschengyf  I followed those steps but I'm still getting the error. On XCode the file libART.a is highlighted red indicating that it is missing. If either of you could send me the file, that could possibly fix everything! Thanks

**Comment by pmarashian** [comment]
I am having the same issue as sampocs.  In XCode the libART.a file is red and adding it to the Link Binary with Libraries section has no effect.

**Comment by ronaldsmartin** [comment]
@sampocs or anyone else still running into this issue:

After linking `libART.a`, I was able to proceed by doing the following
1. In Xcode, use CMD+B to build the project (thus completing the linking process by executing that "Link Binary to Libraries" build phase you just edited)
2. Restart the app by running `react-native run-ios`.

**Hot reloading from the simulator didn't work for me** - I had to restart the app from the command line.

**Comment by brianlow** [comment]
Some additional tips:
* when linking in XCode, make sure to select your main target and not the tvOS or test targets
![image](https://user-images.githubusercontent.com/938138/27805798-0910d8d0-5ff4-11e7-8c4f-4eeeb2b53315.png)


* in XCode -> project navigator -> Libraries -> Products -> libART.a was highlighted in reduntil I ran on device (not the simulator) and restarted XCode
![image](https://user-images.githubusercontent.com/938138/27805813-245b2f32-5ff4-11e7-8ad1-c8c485e3f83d.png)

**Comment by spacegraym3** [comment]
@sschengyf Thanks!  Worked.

**Comment by vipin14119** [comment]
@ronaldsmartin thanks , that exactly the issue, i did'nt knew it that you have to build it , after building and restarting the simulator again, problem fixed 💃

**Comment by deadcoder0904** [comment]
I'm getting the same issue & I followed every single step 5 times & still I get `No component found for view with name "ARTSurfaceView"`

Frustrated now 😂 
Can anyone help 🙏 
I did what @dionysiusmarquis said & what @ronaldsmartin said but its still giving an error in Xcode

**Comment by mealbarracin10** [comment]
I had a same issue, but restart my application, and it solve this problem

**Comment by perrosnk** [comment]
I am having the same problem on RN 0.49.3

**Comment by xe4me** [comment]
https://stackoverflow.com/questions/37658957/no-component-found-for-view-with-name-artshape
helped me

**Comment by yeomann** [comment]
Please please please be make sure that when draging libArt.a make sure the target is your project. 

<img width="1007" alt="screen shot 2018-06-20 at 01 30 06" src="https://user-images.githubusercontent.com/5970751/41627583-83ea564a-7429-11e8-9ca6-3cd7da169320.png">

**Comment by matteocollina** [comment]
It works for me:
1) In my _Podfile_ i entered "**ART**" (my example)

```
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'ART'
  ]
```

2) `pod install` (inside ios folder)
3) `react-native run-ios`
