### ISSUE TITLE
stopped working with react-native 0.26.1

### ISSUE THREAD

**Issue by mathjoy** [bgryszko/react-native-circular-progress#25]

**Comment by corbt** [comment]
I'm not sure what upgrade broke it, but I can confirm that as of the latest version of React Native the `CircularProgress` component doesn't appear to render anything. I'm using it like this:

```jsx
                <CircularProgress
                  fill={(syncInfo.uploadedBytes / syncInfo.uploadTotalBytes) * 100}
                  size={28}
                  width={3}
                  backgroundColor="#bbb"
                  tintColor={navbarColor}
                  style={{ paddingLeft: 18 }}
                />
```

On older versions of React Native this rendered correctly, but now I just get a blank box in my layout where the progress indicator should be.

**Comment by corbt** [comment]
Actually I was running against `master` and my issue was fixed in https://github.com/facebook/react-native/commit/b0fed416cbb510009bef1ae721e564d04d053cc5

**Comment by evollu** [comment]
so it is not an issue anymore?
