### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by EugeneLiang** [bgryszko/react-native-circular-progress#29]
Hi there, 
great module as usual, tried it and works great on iOS and Android!

I was wondering how this module can be used to do infinite loop ?
For example, it will always animate ?

Best Regards.

**Comment by bgryszko** [comment]
Hi @EugeneLiang, I'm not sure I understand the concept you're talking about. You want to make a kind of "loader"? Can you illustrate what do you have in mind?

**Comment by abeikverdi** [comment]
@bgryszko I am also looking for the same thing. In my case I have two circles, one for seconds and the other for minutes. Once the second loop is finished, I want it to start over. Does that make sense?

**Comment by tomauty** [comment]
I think this is just a matter of controlling the fill, no? It will already animate when the fill changes.

**Comment by abeikverdi** [comment]
@tomauty  how do i restart the circular progress once its finished? I need to it to do the same process once fill is 100.

**Comment by bgryszko** [comment]
If I understand correctly, you want be able to animate begining of the circle and then then end of the circle? Something similar to this: 
http://4.bp.blogspot.com/-tqB3UP6KYaM/VItDu0F9kdI/AAAAAAAAATs/QB0X4AqWWY0/s1600/spinningwheel.gif

If so, you'd need to edit this line https://github.com/bgryszko/react-native-circular-progress/blob/master/src/CircularProgress.js#L39 which is `start degree`. We could probably implement this in the core.

If you just want to restart the animation, you can just set fill to `0`, like this:
```
<AnimatedCircularProgress
  size={120}
  width={15}
  fill={0}
  tintColor="#00e0ff"
  backgroundColor="#3d5875" />
```

**Comment by abeikverdi** [comment]
@bgryszko I am not following. I want the later. Just restarting the circle animation.
I start the animation like this:
`    this.refs.circularProgress.performLinearAnimation(100, 60000);
`
and then this is my circle:
```
<AnimatedCircularProgress
            style={styles.innerProgress}
            ref='circularProgress'
            size={140}
            width={10}
            tintColor="#F2F5F8"
            rotation="360"
            backgroundColor="#2FF8FF"/>
```
So basically it works fine and it fills the AnimatedCircularProgress to 100 in 60 seconds. Once its 100, now I want it to do this again. where do i set the fill to 0? and how to call the animation again?

**Comment by abeikverdi** [comment]
Ah hold on. I can put state in the fill and change it from there. This performLinearAnimation made me confused a bit. Thanks for the great library btw. Keep it up.

**Comment by bgryszko** [comment]
Exactly, just use the "fill" prop and control it from your component.

**Comment by abeikverdi** [comment]
cheers! I guess this was the original question. Probably we should close the issue.

**Comment by imarem** [comment]
Hi @abeikverdi could you share your solution, for restarting the circle animation? i have de same problem, using the performLinearAnimation function.

thanks!!

**Comment by bgryszko** [comment]
@imarem, just use state to control the animation fill, like this (without using performAnimation):
```js
<AnimatedCircularProgress
  size={120}
  width={15}
  fill={this.state.animationFill}
  tintColor="#00e0ff"
  backgroundColor="#3d5875" />
```

**Comment by imarem** [comment]
Hi @bgryszko, I'm so sorry, but I'am not following. :(, 

Can you put an example?

Thanks for the quick response!!

**Comment by bgryszko** [comment]
An example is the code above ;-) Can you share the code for the component that you're using AnimatedCircularProgress in?

**Comment by imarem** [comment]
I use a function like this, to run animation during one minute, and then, (when de minute is finish) I want it to do this again.
btnStart = () => {
     this.refs.circularProgress.performLinearAnimation(100, 60000);
  }

The animationFill state, that you mentioned, what value I have to put there to make this scenario?

**Comment by abeikverdi** [comment]
Assuming `animationFill `is your `fill `then just when your fill is 100 then `setState({animationFill: 0})`

**Comment by daaanigm** [comment]
@bartgryszko Did you implement this in the core? Thanks in advance. :) 
 ![spinningwheel](https://cloud.githubusercontent.com/assets/2706504/17324462/eacd9fd4-58a6-11e6-980a-3fc58a7e4a33.gif)
