### ISSUE TITLE
Possible to determine start point?

### ISSUE THREAD

**Issue by tomauty** [bgryszko/react-native-circular-progress#3]
Hi, hopefully this question makes sense. I'd like for my progress circle to go clockwise, however it looks like it starts animating from the right side? 
<img width="213" alt="screen shot 2015-11-25 at 5 20 22 pm" src="https://cloud.githubusercontent.com/assets/1112872/11410864/f8e0293a-9398-11e5-9b26-9ccc8b45e24d.png">

I'm not super familiar with ART, but if I could be led in a direction that would be appreciated as well.

Thanks!

**Comment by bgryszko** [comment]
Hi @tomauty, I've just pushed new version. You can now set `rotation={0}` as described in https://github.com/bgryszko/react-native-circular-progress#configuration to start your progress from the 0* angle.

**Comment by tomauty** [comment]
Thank you!!
