### ISSUE TITLE
Re rendering of component when fill={this.state.number}

### ISSUE THREAD

**Issue by joelwass** [bgryszko/react-native-circular-progress#30]
When this.state.number is updated, the animation is not re rendering. the children of the AnimatedCircularProgress are being updated and re rendered, however the AnimatedCircularProgress itself isn't being re rendered with the animation, etc.

**Comment by bgryszko** [comment]
Can you explain what are you trying to achieve? Did you have a chance to look at the example (https://github.com/bgryszko/react-native-circular-progress/blob/master/example/ProgressChart/main.js) – it is using `state` to control AnimaterCircularProgress fill. Feel free to reopen if needed.
