### ISSUE TITLE
Place text or button inside the circle

### ISSUE THREAD

**Issue by perrosnk** [bgryszko/react-native-circular-progress#32]
Is it possible to place a text or a button inside the circle?
I am trying to do so, following the instructions in the main page, but the text, appears below the circle. 
The only way I can find is to place the text inside using flexbox margin, but I was trying to find a better way.

Thank you!

**Comment by tomauty** [comment]
I usually have one `<View>` as a child of the circle, with a style like this
```javascript
progressContainer: {
	position: 'absolute',
	top: 0,
	left: 0,
	width: <circleWidth>,
	height: <circleHeight>,
	alignItems: 'center',
	justifyContent: 'center',
},
```
