### ISSUE TITLE
Issue running example

### ISSUE THREAD

**Issue by tarang9211** [bgryszko/react-native-circular-progress#33]
I tried to run the example to see how to implement this component.
I received the attached error. Any idea what could this be related to?
<img width="364" alt="screen shot 2016-07-26 at 12 16 01 am" src="https://cloud.githubusercontent.com/assets/5876249/17113051/749674de-52c6-11e6-8294-bd0833ba3f33.png">

I tried following the listed steps to fix the issue, but none worked.

**Comment by CapitanRedBeard** [comment]
If clearing derived data, deleting the app, and running the above commands to start the packager, then the problem is probably something syntactical in your code. Double check variable names and files paths!

**Comment by bgryszko** [comment]
Thanks @CapitanRedBeard for support. As there where no more comments I assume it's fixed.
