### ISSUE TITLE
Is it possible to progress circles one by one?

### ISSUE THREAD

**Issue by ksrawat** [bgryszko/react-native-circular-progress#36]
Hey @bgryszko . Its really fantastic using this component. I was just wondering if you can give me some direction towards one of my edge case?

I have three progress circles but i wanna show them one after another i.e once first one is over, display second, and then third?

How can we achieve this?

**Comment by bgryszko** [comment]
Hi @ksrawat, you fully control the "fill" of progress circles from a component in which you are rendering progress circles (in its state – take a look at the [example](https://github.com/bgryszko/react-native-circular-progress/blob/master/example/ProgressChart/main.js#L57)). You can keep 3 different values in the state for 3 of your circles and show them one after another calculating what's needed before (referring to the example, in your case it could be: fill1, fill2, fill3).
