### ISSUE TITLE
How to fill the circle with 2 different colors

### ISSUE THREAD

**Issue by mvnpgh** [bgryszko/react-native-circular-progress#37]
Hi @bgryszko 
I want to fill a circle with different colors and different points
is it possible with this module.
thanks

**Comment by bgryszko** [comment]
It's possible to change color of the circle 
```
tintColor="#00e0ff"
backgroundColor="#3d5875"
```

You could also have different circles with different colors on top of each other. However if you'd like to have gradient change of the color – it's not implemented so it would need some work. Please explain what exactly you want to achieve.

**Comment by ShaikhKabeer** [comment]
Hi @bgryszko , Here I have attached screenshot . 

![half doughnut](https://user-images.githubusercontent.com/29751540/33884360-5ca8232c-df65-11e7-92f6-83cf01872943.png)

Here is my code

import { AnimatedGaugeProgress, GaugeProgress } from 'react-native-simple-gauge';
import React,{Component} from 'react';
import {View} from 'react-native';

export default class App extends React.Component{
  render(){
    return(
            
      <AnimatedGaugeProgress
      size={200}
      width={20}
      fill={60}
      rotation={90}
      cropDegree={180}
      tintColor="#81BD26"
      strokeCap="square" />
    )
  }
}
