### ISSUE TITLE
Shadow?

### ISSUE THREAD

**Issue by tomauty** [bgryszko/react-native-circular-progress#4]
Hi, it's me again. I think this one might require some more digging and/or a PR, but was wondering if it would be possible to add some type of shadow prop? This way we can create a 'glow' around the progress circle :)

**Comment by bgryszko** [comment]
Hi,

You could try adding style with shadow to a Surface component that is inside or just pass style to a component and see if it works, this way it'll be more universal (as long as it'll render correctly). I'd be happy to accept PR

Bart

**Comment by bgryszko** [comment]
Closing for now. Feel free to submit a PR.

**Comment by VicFrolov** [comment]
@perrosnk I was able to get a shadow working by simply wrapping the AnimatedCircularProgress in a View, and applying a shadow :)
