### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by bfarrgaynor** [bgryszko/react-native-circular-progress#43]
Will this work in android as well as iOS?

**Comment by bgryszko** [comment]
Yes @bfarrgaynor, I've just updated Readme as well as example App to work on Android.

**Comment by bfarrgaynor** [comment]
Amazing thank-you for your efforts @bgryszko! This project saved me a lot of time on a project I was working on. If you need assistance with anything let me know how I can help.

**Comment by bgryszko** [comment]
Sure thing, thanks!
