### ISSUE TITLE
NSInvalidArgumentException on iOS, React Native 0.40

### ISSUE THREAD

**Issue by amsul** [bgryszko/react-native-circular-progress#44]
After upgrading to RN 0.4.0, I am now getting this error:

```
[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0'
```

It's been mentioned (and narrowed down to a specific line) over here: https://github.com/oblador/react-native-progress/issues/40#issue-200216423

There's nothing in the Release Notes that stands out either: https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by airman00** [comment]
So the problem seems to come from react-native-svg

Seems like an NSArray is being passed instead of an NSString somehow

Taking a closer look at it now....

**Comment by jperelli** [comment]
Any progress on this?

**Comment by markusl** [comment]
@amsul @airman00 @jperelli is this still happening with latest version?

**Comment by amsul** [comment]
@markusl nah.. seems like one of the react-native-svg releases fixed it.
