### ISSUE TITLE
Animation progress to move at Clockwise direction?

### ISSUE THREAD

**Issue by larryranches** [bgryszko/react-native-circular-progress#46]
Seems like this module is set to move the animation counter clockwise by default. I've already played with the `rotation` prop with no luck. Is there a way or some sort of `direction` prop to set the animation to to rotate clockwise?

thanks!

**Comment by fdnhkj** [comment]
Here is the code responsible of drawing the circle : https://github.com/bgryszko/react-native-circular-progress/blob/master/src/CircularProgress.js#L10-L20 . 
It uses `Path` object from `art`.
I guess you need to pass that clockwise info there :
https://github.com/sebmarkbage/art/blob/master/core/path.js#L111 .

Let me know if that helps :)

**Comment by bgryszko** [comment]
Happy to accept PR if anybody wants to work on that.

**Comment by Jouddeken** [comment]
@larryranches I don't know if you are still having issues with this, but I fixed it by giving my AnimatedCircularProgress component a style of: `rotateY: '180deg'`.

**Comment by ananyachandra14** [comment]
@Jouddeken Thanks! Although `rotateX: '180deg'` worked for me.

**Comment by ananyachandra14** [comment]
Hey @Jouddeken , this isn't working. Anything apart from this that you also added?

**Comment by ananyachandra14** [comment]
Worked with `scaleY: -1`. Although it inverts the entire view along with the Views/Text inside `fill`. Would be great if it can be passed to `CircularProgress` alone.

**Comment by ckruppe** [comment]
I have an fix for that. Would make a PR if someone grants me access :)

**Comment by ckruppe** [comment]
Got it fixed and also configurable :)

**Comment by markusl** [comment]
Sounds like the issue was fixed!

**Comment by ihsanktmr** [comment]
I used `rotateY` like below is my return. I am using `CircularProgress` and **it worked!**

` return (
      <View style={{...style, transform: [{
          rotateY: '-180deg'
        }]}}>
        <Svg width={size} height={size} scale="-1, 1" originX={size / 2}>
          <Defs key="linear_gradients">{linearGradients}</Defs>
          <G rotate={rotation - 90}>
            {this.renderBackgroundPath()}
            {this.renderCirclePaths()}
          </G>
        </Svg>
        {children && children(fill)}
      </View>
    );`

**Comment by Rokeshrk** [comment]
I have done this using styled components with the transform property.

`const StyledProgress = styled(Progress)`
  .ant-progress-circle {
    transform: scaleY(-1) rotate(-180deg);
  }

  .ant-progress-text {
    color: black !important;
  }
`
`
