### ISSUE TITLE
Trying to use performLinearAnimation(toValue, duration)

### ISSUE THREAD

**Issue by Louis345** [bgryszko/react-native-circular-progress#48]
First, I want to say thank you so much for taking the time for making such an awesome component. 

I am trying to build a Pomodoro timer and would like to take advantage of the performLinear Animation prop, but I am having a bit of trouble implementing it. I ls there a simple example you can direct me to?

Thank you in advance.

**Comment by bgryszko** [comment]
Hey, in most cases you just need to use state for controling fill. Like that:

<AnimatedCircularProgress
  fill={this.state.fill}

**Comment by Louis345** [comment]
Thank it works.
