### ISSUE TITLE
linecap doesn't work

### ISSUE THREAD

**Issue by Mactub07** [bgryszko/react-native-circular-progress#53]
it seems that linecap property doesn't work as well.

for ex: 
<AnimatedCircularProgress
                                ref='circularProgress'
                                size={200}
                                width={25}
                                fill={this.state.fill}
                                tintColor="yellow"
                                backgroundColor="#3d5875"
                                onLayout={(e)=> console.log(e)}
                                linecap = 'round'
                            >

                            </AnimatedCircularProgress>
                            <AnimatedCircularProgress
                                ref='circularProgress'
                                size={150}
                                width={25}
                                fill={this.state.fill}
                                tintColor="red"
                                backgroundColor="#3d5875"
                                onLayout={(e)=> console.log(e)}
                                linecap = {'round'}
                            >
                            </AnimatedCircularProgress>
![screenshot at 06 19-01-36](https://cloud.githubusercontent.com/assets/13048119/23620389/5ed99c96-029f-11e7-8bf2-20cf1ae78364.png)

**Comment by sytolk** [comment]
linecap='round' works for me
```
<AnimatedCircularProgress
                    ref={ref => {
                        this.speedProgress = ref;
                    }}
                    style={{position: "absolute"}}
                    size={circleSize}
                    width={35}
                    fill={initSpeed}
                    tintColor={speedProgressColor}
                    backgroundColor="#fff"
                    linecap='round'
                    rotation={90}
                    arcSweepAngle={280}
                >
```

**Comment by Mactub07** [comment]
Yes, because module was updated , unfortunally I dont see increase vesion number, for install the latest one we need "npm install react-native-circular-progress@latest" in case if you've have this module yet and want to get the latest version

**Comment by sytolk** [comment]
Thanks @Mactub07 but I'm just copy the source code of this library in my project (it`s have 2 JavaScript files only). The reason that I`m not using `npm install` is that PR like https://github.com/bgryszko/react-native-circular-progress/pull/50 and https://github.com/bgryszko/react-native-circular-progress/pull/38 is not merged yet :) If you need this functionality you can include it with `npm install git+https://github.com/sytolk/react-native-circular-progress.git` from my fork :)

**Comment by renso3x** [comment]
@sytolk hi I have used your library and it's great. But I have a problem with the stroke caps.

![screen shot 2017-09-20 at 8 39 32 am](https://user-images.githubusercontent.com/16775150/30621979-2f17c48c-9de1-11e7-8657-4b7ed9e47437.png)

Can you help how to give a padding inside a surface.?

**Comment by markusl** [comment]
Hi @Mactub07 ! Is this still a problem with the latest version?

**Comment by Mactub07** [comment]
actually I dont know how it works with the latest version, at least it works for me when I use "react-native-circular-progress": "0.0.8",

**Comment by Jacse** [comment]
Closing since this appears to be fixed. Please re-open if that is not the case.

**Comment by hansa0712004212** [comment]
Linecap is not working on v 1.1.0.
Please help

**Comment by Mactub07** [comment]
@hansa0712004212, as I see in code of this module you should use 'lineCap' instead of 'linecap'

**Comment by hansa0712004212** [comment]
> @hansa0712004212, as I see in code of this module you should use 'lineCap' prop name instead of 'linecap' (like you text in example code)

Sorry. Typo error.
Well that is not problem. Here is my final code.
```
<AnimatedCircularProgress
                  ref={(ref) => this.circularProgress = ref}
                  size={150} width={10} rotation={0} fill={progress}
                  tintColor={Colors.primary.lightRed} backgroundColor={"rgba(0, 0, 0, 0.2)"} lineCap={"round"}>
```
Still lineCap is missing.
See screenshot [here](https://i.imgur.com/h0wnNWE.jpg).
