### ISSUE TITLE
Exception on android sdk 19

### ISSUE THREAD

**Issue by ofirgeller** [bgryszko/react-native-circular-progress#59]
Android sdk 19 on both a real device and on emulator
When using AnimatedCircularProgress with react native 0.43.1

the log shows 

/ReactNativeJS(31009): Module AppRegistry is not a registered callable module (calling runApplication)
E/ReactNativeJS(31009): Requiring module "94", which threw an exception.

And then the exception "undefined is not an object (evaluating undefined.hex)" is thrown.

If you have any ideas how to fix i'm happy to do some work myself on the code.

**Comment by himelbrand** [comment]
simillar issue, with react native 0.43.4 and sdk 23

**Comment by markusl** [comment]
@himelbrand @ofirgeller is this problem still happening with latest version?

**Comment by markusl** [comment]
Please reopen if the issue still persists.
