### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by jasalo** [bgryszko/react-native-circular-progress#6]
I haven't been able to include react-native-circular-progress in my project. It gives me an:
`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
Also, console logs this just before:
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). `
Any clue of what might be happening?

**Comment by bgryszko** [comment]
Hi, double check if you've followed installation instructions. Are you able to run the example app that you can find in this repo? 

Bart

**Comment by bgryszko** [comment]
I've run int similar issue, please update to `v. 0.0.3`, and let me know if that helps. Reopen if needed.

**Comment by bickerstoff** [comment]
I ran into the same issue with the latest version.  I double checked the installation instructions and here is what worked for me:

I had the following with (which generated the error)
`const AnimatedCircularProgress = require('react-native-circular-progress');`

I changed it to this (which is what is listed in the installation instructions)
`import { AnimatedCircularProgress } from 'react-native-circular-progress';`

**Comment by tomauty** [comment]
Yeah, if you're using `require` you would do it like `const AnimatedCircularProgress = require('react-native-circular-progress').AnimatedCircularProgress;`
