### ISSUE TITLE
Add prop for loading animation

### ISSUE THREAD

**Issue by andreiciceu** [bgryszko/react-native-circular-progress#63]
Hello,

Firstly, congrats for your work.
I think it would be useful to add a `loading` prop that, when set to `true` would cause the circle progress to spin. Like here for example [https://github.com/oblador/react-native-progress](https://github.com/oblador/react-native-progress)
Although this can be obtained by updating the angle of the component periodically, it's not an efficient way of doing it, as a re-render is triggered every time the state updates.

Thank you

**Comment by markusl** [comment]
Hi @andreiciceu ! Is this request still needed with the latest version?

Best Regards,
Markus

**Comment by andreiciceu** [comment]
Hi @markusl !
Nope, it's not needed anymore. I achieved that using ActivityIndicator.

Best regards,
Andrei
