### ISSUE TITLE
Breaks on react-native 0.45.1

### ISSUE THREAD

**Issue by nielsswinkels** [bgryszko/react-native-circular-progress#64]
When I update to react-native 0.45.1 the drawing is no longer a circle, only partly (tested on new empty android project). Unfortunately I haven't been able to dive into the issue and look for a more detailed problem description. Downgrading to RN 0.44.1 made it work again.

**Comment by peacerevolution** [comment]
I think I'm facing similar problems. Is this something you are facing?

iOS

![simulator screen shot jun 19 2560 be 4 57 19 pm](https://user-images.githubusercontent.com/4251613/27280023-aa6dcaf6-5510-11e7-97f9-7d64ad8e493f.png)

Android

![screenshot_1497866242](https://user-images.githubusercontent.com/4251613/27280032-ae6cce2c-5510-11e7-8eac-beab087ac939.png)

**Comment by laclance** [comment]
![circle](https://user-images.githubusercontent.com/10835285/27281986-76bb56be-54ee-11e7-978c-1db9c365c3aa.jpeg)

**Comment by insidelabs** [comment]
We had to fork this to get it working on Android. The Android specific circlePath render appears to no longer be relevant.

https://github.com/insidelabs/react-native-circular-progress/commit/450108f5d6ddf8c0c6db141531388852c787419a
https://github.com/insidelabs/react-native-circular-progress/commit/d21a41e3a035eb65a517ed28f99a5ef96d2f1ee4
https://github.com/insidelabs/react-native-circular-progress/commit/0006c55d46f79fd12b26ee63a2a7da20f78a7769

**Comment by walkerXiong** [comment]
+1 RN version: 0.45.1

**Comment by andreiciceu** [comment]
Hi, I've createad a PR solving this issue:
andreiciceu/react-native-circular-progress#86919eb

**Comment by andreiciceu** [comment]
Hi, I've createad a PR solving this issue:
#86919eb

**Comment by douglasjunior** [comment]
Is this repository abandoned?

**Comment by SoundBlaster** [comment]
While npm is not updated you can use
`"react-native-circular-progress": "git+https://github.com/bgryszko/react-native-circular-progress.git",`
in package.json

**Comment by markusl** [comment]
It seems that the issue is solved in latest version.
