### ISSUE TITLE
Not rendering after lock-unlock

### ISSUE THREAD

**Issue by andreiciceu** [bgryszko/react-native-circular-progress#65]
On the device, when performing a lock (via hard button or after screen being idle for 30+secs) and unlocking, sometimes the progress indicator is not rendered. After navigating back-forth, the progress is shown

**Comment by masterpetit** [comment]
I encounter the same bug but only on Android. The render function is called and everything seems to be fine but the component is not visible. The inspector shows no changes when the component is not visible after lock.

**Comment by kelvinlawson** [comment]
Yes it is Android only. I ended up using an AppState callback to restart the animation when the app returns to the foreground (I'm using AnimatedCircularProgress).

**Comment by gamingumar** [comment]
@kelvinlawson can you share how you fixed it?

**Comment by kelvinlawson** [comment]
@gamingumar, here is my patch: https://gist.github.com/kelvinlawson/01985972c333f4690951daff20b4dabf

**Comment by gamingumar** [comment]
thanks @kelvinlawson is it safe to use these events? aren't they going to be deprecated?

**Comment by Jacse** [comment]
#95 fixes this. Let's hope we can get it merged soon and keep discussion over there for now.
