### ISSUE TITLE
is there any way?...

### ISSUE THREAD

**Issue by cinder92** [bgryszko/react-native-circular-progress#66]
Hello thanks for your grate plugin! is there any way to do something like this?

![captura de pantalla 2017-06-19 a la s 20 17 27](https://user-images.githubusercontent.com/4725556/27312342-4ae16dc8-552d-11e7-8f58-ddf9be3fb472.png)

regards!

**Comment by jkomyno** [comment]
You may want to check this repo: https://github.com/bgryszko/react-native-circular-slider
