### ISSUE TITLE
Animated Handler 

### ISSUE THREAD

**Issue by renso3x** [bgryszko/react-native-circular-progress#78]
Hi guys, 

How do I achieve the track bottom the circular white?

![screen shot 2017-09-04 at 7 49 57 am](https://user-images.githubusercontent.com/16775150/30007639-52a5bc76-9146-11e7-8081-4abc515a74cb.png)

**Comment by Jacse** [comment]
I'm not exactly sure what you mean. If this is still an issue could you clarify? Otherwise I'll be closing.
