### ISSUE TITLE
Android RN 0.48.2 

### ISSUE THREAD

**Issue by Mad-hu** [bgryszko/react-native-circular-progress#80]
![qq20170911-164356-hd 1](https://user-images.githubusercontent.com/13977755/30266408-da79155a-9711-11e7-995e-84a4b192b12b.gif)

"react-native-circular-progress": "^0.0.8",
npm version 
 0.0.8': '2016-12-23T09:34:56.994Z' },
  homepage: 'https://github.com/bgryszko/react-native-circular-progress 

If you have a new version, please update the NPM,thx
![khkk0 4urpre jxs zc36en](https://user-images.githubusercontent.com/13977755/30266638-a1845a74-9712-11e7-9123-ce187215eff9.jpg)

**Comment by Mad-hu** [comment]
Manual updates, but there are problems
change prop size bigger

![qq 20170912160647](https://user-images.githubusercontent.com/13977755/30314872-ad7af384-97d4-11e7-9b38-61cd0c4f3dbd.jpg)

![qq 20170912160652](https://user-images.githubusercontent.com/13977755/30314891-b6cbf88e-97d4-11e7-9a68-81c5f6539219.jpg)

![qq 20170912160655](https://user-images.githubusercontent.com/13977755/30314892-b6d858ea-97d4-11e7-9a24-ca954e4f20d4.jpg)

**Comment by MrFlox** [comment]
Same problem

**Comment by ssomnoremac** [comment]
@Mad-hu @MrFlox #72 has a solution

**Comment by markusl** [comment]
Closing as duplicate
