### ISSUE TITLE
PropTypes no longer supported

### ISSUE THREAD

**Issue by ARMATAV** [bgryszko/react-native-circular-progress#85]
Hey, minor error at CircularProgress.js:66 onward.

> Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

**Comment by markusl** [comment]
This is now fixed in the npm package.
