### ISSUE TITLE
AnimatedCircularProgress is still using React.PropTypes, RN 0.49.0 will not work

### ISSUE THREAD

**Issue by ovaris** [bgryszko/react-native-circular-progress#86]
React.PropTypes no longer exists in 0.49.0 ....

See related https://github.com/bgryszko/react-native-circular-progress/issues/85

**Comment by ovaris** [comment]
It seems that it's already fixed in master but not yet published to npm.

**Comment by ovaris** [comment]
Another issue came up trying to run in release mode, PR here https://github.com/bgryszko/react-native-circular-progress/pull/87

**Comment by zarcode** [comment]
please merge this

**Comment by markusl** [comment]
This is now fixed!
