### ISSUE TITLE
No component found for view with name "RNSVGDefs"

### ISSUE THREAD

**Issue by fabiancarlos** [bgryszko/react-native-circular-progress#88]
hi guys, this is a problem with the react-native-svg?? There is a way to not use they?

![errs_svg](https://user-images.githubusercontent.com/636804/31368887-8ce0af3a-ad4e-11e7-8b3b-27782030ba41.png)

**Comment by markusl** [comment]
Do you have any more details on this?

**Comment by fabiancarlos** [comment]
i'm not using this component for a now, i will see later. So, i will close it for now.
