### ISSUE TITLE
Cannot read property 'slice' of null while setting background color to 'transparent'

### ISSUE THREAD

**Issue by MiguelGrenho** [bgryszko/react-native-circular-progress#90]
I'm getting a problem setting the background color to "transparent", although it accepts things like 'red', 'white'. 

Does this library supports transparent background color? Has anyone encountered this issue ? 

![error](https://user-images.githubusercontent.com/5865757/31659859-65af7ee8-b32d-11e7-88fd-0c73e102d02b.png)

**Comment by Jacse** [comment]
It supports a transparent background now 👍

**Comment by lefoy** [comment]
@Jacse can you please publish a new version with this fix? The latest NPM package doesn't include this fix. Thank you 👍

**Comment by lefoy** [comment]
Looking at other issues it seems that @markusl is doing the npm versions. If you have time to publish a new version for this fix it would be much appreciated. Thank you 👍

**Comment by Jacse** [comment]
@lefoy so sorry I completely threw this out of my head. I've release v2.0.0 now.

**Comment by iDuuck** [comment]
Still getting the error on v0.2.0...
